export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const INPUT_FILTER_KEY = 'INPUT_FILTER_KEY';

export const GET_TIME_REQUEST = 'GET_TIME_REQUEST';
export const GET_TIME_FAILURE = 'GET_TIME_FAILURE';
export const GET_TIME_SUCCESS = 'GET_TIME_SUCCESS';

export const GET_TIME_ERROR_CLEAR = 'GET_TIME_ERROR_CLEAR';